### GET all tasks
GET http://localhost:3000/v1/tasks
Content-Type: application/json
Accept: application/json

### GET task by id
GET http://localhost:3000/v1/tasks/5
Content-Type: application/json
Accept: application/json

### Create new task
POST http://localhost:3000/v1/tasks
Content-Type: application/json
Accept: application/json

{
  "title": "task test 2",
  "description": "description of task test"
}

### Update task
PATCH http://localhost:3000/v1/tasks/6
Content-Type: application/json
Accept: application/json

{
  "status": "ON_PROGRESS"
}

### Delete task
DELETE http://localhost:3000/v1/tasks/6
Content-Type: application/json
Accept: application/json