### GET all tasks
GET http://localhost:3000/v1/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RpZCI6IjMyMjUxYzNjLTQ1N2YtNGJlZi1iMzNmLTlmMjFmMmRkMDFmZiIsInN1YiI6MTksIm5hbWUiOiJCb2IgQWxleCIsImVtYWlsIjoiYm9iQGFsZXguY29tIiwiaWF0IjoxNzMzMTY5MjE4LCJleHAiOjE3MzMxNzI4MTgsImF1ZCI6ImthbmJhbi1iZSIsImlzcyI6ImthbmJhbi1iZSJ9.v25ZCw-CwNPdTjiqvWIB2d6-oH4c-pxC_cbW1aaQcyE

### GET task by id
GET http://localhost:3000/v1/tasks/18
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RpZCI6ImUxMDMwMGVjLTUxMGUtNDBiNy1iMzM5LTYxYjlkNjA0ODNhMiIsInN1YiI6MTksIm5hbWUiOiJCb2IgQWxleCIsImVtYWlsIjoiYm9iQGFsZXguY29tIiwiaWF0IjoxNzMzMDcwMzQ3LCJleHAiOjE3MzMwNzM5NDcsImF1ZCI6ImthbmJhbi1iZSIsImlzcyI6ImthbmJhbi1iZSJ9.ZEHtdM3sOCbnoERPsrPMgZvTIUlzy9FRjlhQdVW7uCI

### Create new task
POST http://localhost:3000/v1/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RpZCI6IjMyMjUxYzNjLTQ1N2YtNGJlZi1iMzNmLTlmMjFmMmRkMDFmZiIsInN1YiI6MTksIm5hbWUiOiJCb2IgQWxleCIsImVtYWlsIjoiYm9iQGFsZXguY29tIiwiaWF0IjoxNzMzMTY5MjE4LCJleHAiOjE3MzMxNzI4MTgsImF1ZCI6ImthbmJhbi1iZSIsImlzcyI6ImthbmJhbi1iZSJ9.v25ZCw-CwNPdTjiqvWIB2d6-oH4c-pxC_cbW1aaQcyE

{
  "title": "task test 2",
  "description": "description of task 2"
}

### Update task
PATCH http://localhost:3000/v1/tasks/123
Content-Type: application/json
Accept: application/json

{
  "status": "ON_PROGRESS"
}

### Delete task
DELETE http://localhost:3000/v1/tasks/600
Content-Type: application/json
Accept: application/json